use tauri::ipc::Invoke;
use tauri::Wry;

use crate::{
    appbar, apps, audio, chat_window, claude, clipboard, desktop, edit, features, files, icons,
    media, meters, monitors, notices, notify, preview, quick, shortcuts, spectrum, system, usage,
    windowing, winkey,
};

pub fn handler() -> impl Fn(Invoke<Wry>) -> bool + Send + Sync + 'static {
    tauri::generate_handler![
        apps::list_apps,
        apps::pinned_apps,
        apps::launch_app,
        apps::open_location,
        files::list_dir,
        files::file_places,
        files::search_dir,
        files::create_folder,
        files::rename_entry,
        files::delete_entries,
        files::transfer_entries,
        icons::app_icon,
        desktop::list_windows,
        desktop::activate_window,
        desktop::close_window,
        desktop::minimize_window,
        preview::preview_show,
        preview::preview_hide,
        system::system_accent,
        system::system_info,
        system::power_action,
        system::empty_recycle_bin,
        system::open_url,
        system::run_command,
        system::machine_name,
        system::open_data_folder,
        icons::clear_icon_cache,
        audio::set_volume,
        audio::toggle_mute,
        audio::audio_devices,
        audio::set_audio_device,
        appbar::apply_taskbar,
        appbar::extend_taskbar,
        monitors::list_monitors,
        media::media_status,
        media::media_command,
        meters::system_meters,
        spectrum::spectrum_start,
        spectrum::spectrum_stop,
        usage::claude_usage,
        usage::usage_bridge_installed,
        usage::install_usage_bridge,
        notify::notify_icons,
        notify::notify_icon_click,
        notify::notify_icon_promote,
        quick::radios,
        quick::set_radio,
        quick::bluetooth_devices,
        quick::quick_action,
        quick::input_language,
        quick::cycle_input_language,
        winkey::set_win_key_capture,
        shortcuts::set_launcher_shortcut,
        shortcuts::set_chat_shortcut,
        windowing::show_window,
        windowing::hide_window,
        windowing::toggle_window,
        claude::claude_which,
        claude::claude_start,
        claude::claude_send,
        claude::claude_stop,
        claude::claude_sessions,
        claude::claude_transcript,
        features::set_features,
        edit::edit_mode,
        notices::notices_list,
        notices::notices_unseen,
        notices::notices_seen,
        notices::notices_dismiss,
        notices::notices_open_panel,
        notices::notices_take_intent,
        edit::edit_raise,
        chat_window::chat_area,
        chat_window::chat_frame,
        clipboard::clipboard_history,
        clipboard::clipboard_copy,
        clipboard::clipboard_paste,
        clipboard::clipboard_remove,
        clipboard::clipboard_pin,
        clipboard::clipboard_clear,
    ]
}
