import { score } from "./search"

const TABLE: [string, string, string][] = [
  ["😀", "grinning", "smile happy face"],
  ["😃", "smiley", "happy joy grin"],
  ["😄", "smile", "happy laugh joy"],
  ["😁", "beaming", "grin happy teeth"],
  ["😆", "laughing", "lol haha satisfied"],
  ["😅", "sweat smile", "relief nervous laugh"],
  ["🤣", "rofl", "lol rolling laughing floor"],
  ["😂", "joy", "lol tears laugh cry"],
  ["🙂", "slight smile", "happy content"],
  ["🙃", "upside down", "silly sarcasm irony"],
  ["😉", "wink", "flirt joke"],
  ["😊", "blush", "happy shy smile"],
  ["😇", "innocent", "angel halo"],
  ["🥰", "smiling hearts", "love adore crush"],
  ["😍", "heart eyes", "love crush adore"],
  ["😘", "kiss", "love blow kiss"],
  ["😋", "yum", "tongue tasty delicious"],
  ["😜", "wink tongue", "silly joke crazy"],
  ["🤪", "zany", "crazy goofy wild"],
  ["🤗", "hug", "hugging embrace"],
  ["🤭", "hand over mouth", "oops giggle"],
  ["🤫", "shush", "quiet silence secret"],
  ["🤔", "thinking", "hmm consider think"],
  ["🤐", "zipper mouth", "silence secret quiet"],
  ["😐", "neutral", "meh blank deadpan"],
  ["😑", "expressionless", "blank meh"],
  ["😶", "no mouth", "silence blank speechless"],
  ["😏", "smirk", "smug sly"],
  ["😒", "unamused", "meh annoyed unimpressed"],
  ["🙄", "eye roll", "annoyed whatever"],
  ["😬", "grimace", "awkward eek yikes"],
  ["😌", "relieved", "calm content"],
  ["😔", "pensive", "sad down"],
  ["😴", "sleeping", "zzz asleep tired"],
  ["😷", "mask", "sick ill medical"],
  ["🤢", "nauseated", "sick gross yuck"],
  ["🥵", "hot face", "heat sweating overheated"],
  ["🥶", "cold face", "freezing frozen ice"],
  ["😵", "dizzy", "knocked out confused"],
  ["🤯", "mind blown", "explode shock wow"],
  ["🤠", "cowboy", "hat yeehaw"],
  ["🥳", "partying", "celebrate birthday party"],
  ["😎", "sunglasses", "cool shades"],
  ["🤓", "nerd", "geek glasses smart"],
  ["🧐", "monocle", "inspect scrutiny curious"],
  ["😕", "confused", "puzzled unsure"],
  ["😟", "worried", "concerned anxious"],
  ["😮", "open mouth", "surprise wow shock"],
  ["😲", "astonished", "shocked amazed gasp"],
  ["🥺", "pleading", "puppy eyes beg please"],
  ["😢", "cry", "sad tear upset"],
  ["😭", "sobbing", "cry sad bawling"],
  ["😤", "triumph", "steam angry proud"],
  ["😠", "angry", "mad annoyed"],
  ["😡", "rage", "furious mad red"],
  ["🤬", "cursing", "swearing angry symbols"],
  ["😱", "scream", "fear shock horror"],
  ["😨", "fearful", "scared afraid"],
  ["🥱", "yawn", "bored tired sleepy"],
  ["😈", "smiling devil", "evil imp mischief"],
  ["💀", "skull", "dead death rip"],
  ["👻", "ghost", "halloween spooky boo"],
  ["👽", "alien", "ufo space extraterrestrial"],
  ["🤖", "robot", "bot ai machine"],
  ["💩", "poop", "crap shit turd"],
  ["🤡", "clown", "circus joker"],
  ["👋", "wave", "hello hi bye greeting"],
  ["✋", "raised hand", "stop high five palm"],
  ["👌", "ok hand", "perfect fine nice"],
  ["🤏", "pinch", "small tiny little"],
  ["✌️", "victory", "peace two fingers"],
  ["🤞", "fingers crossed", "luck hope wish"],
  ["🤟", "love you gesture", "hand ily"],
  ["🤘", "rock on", "horns metal"],
  ["👈", "point left", "left direction"],
  ["👉", "point right", "right direction"],
  ["👆", "point up", "up above"],
  ["👇", "point down", "down below"],
  ["👍", "thumbs up", "like yes approve good lgtm"],
  ["👎", "thumbs down", "dislike no bad"],
  ["✊", "raised fist", "power solidarity"],
  ["👊", "fist bump", "punch bro"],
  ["👏", "clap", "applause bravo praise"],
  ["🙌", "raised hands", "celebrate praise hooray"],
  ["🤝", "handshake", "deal agree partner"],
  ["🙏", "pray", "thanks please namaste hope"],
  ["💪", "muscle", "strong flex biceps"],
  ["🧠", "brain", "smart think mind"],
  ["👀", "eyes", "look watch see"],
  ["🫡", "salute", "respect yes sir"],
  ["🫠", "melting", "hot awkward dissolve"],
  ["👶", "baby", "infant child"],
  ["🧑", "person", "adult human"],
  ["👨", "man", "male guy"],
  ["👩", "woman", "female lady"],
  ["🧑‍💻", "technologist", "developer coder programmer"],
  ["👑", "crown", "king queen royal"],
  ["🐶", "dog", "puppy pet doggo"],
  ["🐱", "cat", "kitten kitty pet"],
  ["🐰", "rabbit", "bunny easter"],
  ["🦊", "fox", "sly"],
  ["🐻", "bear", "grizzly"],
  ["🐼", "panda", "bear china"],
  ["🐯", "tiger", "big cat"],
  ["🦁", "lion", "king jungle"],
  ["🐮", "cow", "moo cattle"],
  ["🐷", "pig", "oink pork"],
  ["🐸", "frog", "toad ribbit"],
  ["🙈", "see no evil", "monkey hide shy"],
  ["🐔", "chicken", "hen poultry"],
  ["🐧", "penguin", "antarctica bird"],
  ["🦅", "eagle", "bird hawk"],
  ["🦉", "owl", "night wise bird"],
  ["🐴", "horse", "pony"],
  ["🦄", "unicorn", "magic fantasy"],
  ["🐝", "bee", "honey buzz"],
  ["🐛", "bug", "insect caterpillar defect"],
  ["🦋", "butterfly", "insect"],
  ["🐢", "turtle", "slow tortoise"],
  ["🐍", "snake", "python serpent"],
  ["🐙", "octopus", "tentacles"],
  ["🐳", "whale", "ocean"],
  ["🐟", "fish", "ocean"],
  ["🦈", "shark", "ocean jaws"],
  ["🐘", "elephant", "trunk"],
  ["🌵", "cactus", "desert plant"],
  ["🌲", "evergreen", "tree pine forest"],
  ["🌳", "tree", "forest deciduous"],
  ["🌴", "palm tree", "tropical beach"],
  ["🌱", "seedling", "sprout plant grow"],
  ["🌿", "herb", "leaf plant"],
  ["🍀", "four leaf clover", "luck lucky irish"],
  ["🌸", "cherry blossom", "sakura spring flower"],
  ["🌹", "rose", "flower love"],
  ["🌻", "sunflower", "flower yellow"],
  ["🍁", "maple leaf", "canada autumn fall"],
  ["🍄", "mushroom", "fungus toadstool"],
  ["🍎", "apple", "fruit red"],
  ["🍌", "banana", "fruit"],
  ["🍓", "strawberry", "fruit berry"],
  ["🍊", "orange", "fruit tangerine citrus"],
  ["🍋", "lemon", "fruit citrus sour"],
  ["🍉", "watermelon", "fruit summer"],
  ["🥑", "avocado", "fruit toast"],
  ["🍅", "tomato", "vegetable"],
  ["🥕", "carrot", "vegetable"],
  ["🌽", "corn", "maize vegetable"],
  ["🍞", "bread", "loaf toast"],
  ["🥐", "croissant", "pastry french"],
  ["🧀", "cheese", "dairy"],
  ["🍳", "fried egg", "cooking breakfast pan"],
  ["🍔", "burger", "hamburger fast food"],
  ["🍟", "fries", "chips fast food"],
  ["🍕", "pizza", "slice italian"],
  ["🌭", "hot dog", "sausage"],
  ["🌮", "taco", "mexican"],
  ["🍜", "ramen", "noodles soup"],
  ["🍣", "sushi", "japanese fish"],
  ["🍱", "bento", "japanese lunch box"],
  ["🥗", "salad", "healthy greens"],
  ["🍰", "cake slice", "dessert birthday"],
  ["🎂", "birthday cake", "party celebrate"],
  ["🍪", "cookie", "biscuit dessert"],
  ["🍫", "chocolate", "candy sweet"],
  ["🍩", "donut", "doughnut dessert"],
  ["🍦", "ice cream", "dessert soft serve"],
  ["☕", "coffee", "hot drink cafe tea"],
  ["🍵", "tea", "green tea drink"],
  ["🍺", "beer", "drink pint pub"],
  ["🍻", "cheers", "beers toast drink"],
  ["🍷", "wine", "drink glass red"],
  ["🥂", "champagne", "toast celebrate cheers"],
  ["💧", "droplet", "water drop"],
  ["🚗", "car", "auto drive vehicle"],
  ["🚌", "bus", "transit"],
  ["🚑", "ambulance", "emergency medical"],
  ["🚲", "bicycle", "bike cycling"],
  ["🏍️", "motorcycle", "bike motorbike"],
  ["🚚", "truck", "delivery lorry"],
  ["🚂", "train", "locomotive rail"],
  ["✈️", "airplane", "flight travel plane"],
  ["🚀", "rocket", "launch space ship deploy"],
  ["🛸", "ufo", "flying saucer alien"],
  ["🚢", "ship", "cruise boat"],
  ["🏠", "house", "home building"],
  ["🏢", "office", "building work"],
  ["🏫", "school", "education building"],
  ["🌍", "earth", "globe world europe africa"],
  ["🌏", "globe asia", "earth world asia"],
  ["🌙", "moon", "night crescent"],
  ["⭐", "star", "favorite rating"],
  ["🌟", "glowing star", "sparkle shine"],
  ["✨", "sparkles", "shiny magic new clean"],
  ["⚡", "lightning", "bolt fast power zap"],
  ["🔥", "fire", "hot lit flame burn"],
  ["🌈", "rainbow", "pride colors"],
  ["☀️", "sun", "sunny clear weather"],
  ["☁️", "cloud", "weather overcast"],
  ["🌧️", "rain", "weather shower"],
  ["⛈️", "thunderstorm", "weather storm lightning"],
  ["❄️", "snowflake", "snow cold winter"],
  ["🌊", "wave", "ocean sea water"],
  ["🎉", "party popper", "celebrate congrats tada"],
  ["🎈", "balloon", "party birthday"],
  ["🎁", "gift", "present birthday"],
  ["🏆", "trophy", "win award champion"],
  ["🥇", "gold medal", "first win"],
  ["🎯", "target", "bullseye dart goal"],
  ["🎮", "game controller", "gaming video game"],
  ["🎧", "headphones", "music audio listen"],
  ["🎵", "music note", "song audio"],
  ["🎤", "microphone", "sing karaoke record"],
  ["🎬", "clapper", "movie film action"],
  ["📷", "camera", "photo picture"],
  ["📱", "phone", "mobile smartphone"],
  ["💻", "laptop", "computer macbook code"],
  ["🖥️", "desktop", "computer monitor pc"],
  ["⌨️", "keyboard", "typing keys"],
  ["🖱️", "mouse device", "pointer click"],
  ["🖨️", "printer", "print paper"],
  ["💾", "floppy", "save disk"],
  ["🔋", "battery", "power charge"],
  ["🔌", "plug", "power electricity"],
  ["💡", "bulb", "idea light tip"],
  ["🔍", "magnifier", "search find zoom"],
  ["🔒", "lock", "secure private closed"],
  ["🔓", "unlock", "open insecure"],
  ["🔑", "key", "password access"],
  ["🔨", "hammer", "build tool fix"],
  ["🔧", "wrench", "tool fix config"],
  ["⚙️", "gear", "settings config cog"],
  ["🧰", "toolbox", "tools repair"],
  ["🧪", "test tube", "lab experiment science"],
  ["🔬", "microscope", "science lab research"],
  ["💊", "pill", "medicine drug"],
  ["📦", "package", "box shipping parcel deps"],
  ["✉️", "envelope", "mail email letter"],
  ["📝", "memo", "note write edit"],
  ["📄", "page", "document file"],
  ["📁", "folder", "directory files"],
  ["📊", "bar chart", "graph stats data"],
  ["📈", "chart up", "growth increase trend"],
  ["📉", "chart down", "loss decrease drop"],
  ["📌", "pin", "pushpin location mark"],
  ["📎", "paperclip", "attach clip"],
  ["✂️", "scissors", "cut trim"],
  ["📅", "calendar", "date schedule"],
  ["⏰", "alarm clock", "time wake reminder"],
  ["⏳", "hourglass", "time waiting loading"],
  ["⌚", "watch", "time wrist"],
  ["💰", "money bag", "cash rich profit"],
  ["💳", "credit card", "payment pay"],
  ["💎", "gem", "diamond jewel precious"],
  ["🛒", "cart", "shopping buy"],
  ["🔔", "bell", "notification alert ring"],
  ["🔕", "bell off", "mute silence notification"],
  ["📢", "loudspeaker", "announce shout"],
  ["🚩", "red flag", "mark report"],
  ["♻️", "recycle", "reuse environment"],
  ["⚠️", "warning", "caution alert danger"],
  ["🚫", "prohibited", "no ban forbidden"],
  ["✅", "check mark", "done yes complete pass"],
  ["❌", "cross mark", "no wrong fail delete"],
  ["❓", "question", "ask help unknown"],
  ["❗", "exclamation", "important alert"],
  ["💯", "hundred", "perfect score full"],
  ["❤️", "red heart", "love like"],
  ["🖤", "black heart", "love dark"],
  ["💔", "broken heart", "sad breakup"],
  ["💬", "speech balloon", "comment chat message"],
  ["💤", "zzz", "sleep tired snore"],
  ["🇰🇷", "korea flag", "south korea kr"],
  ["🇺🇸", "usa flag", "united states america us"],
  ["🇯🇵", "japan flag", "jp nippon"],
  ["🇬🇧", "uk flag", "britain england gb"],
  ["🇫🇷", "france flag", "fr french"],
  ["🇩🇪", "germany flag", "de deutschland"],
  ["🇨🇦", "canada flag", "ca"],
  ["🇦🇺", "australia flag", "au"],
  ["🏳️‍🌈", "rainbow flag", "pride lgbt"],
  ["→", "right arrow", "arrow east next"],
  ["←", "left arrow", "arrow west back"],
  ["↑", "up arrow", "arrow north"],
  ["↓", "down arrow", "arrow south"],
  ["↔", "left right arrow", "arrow both"],
  ["⇒", "double right arrow", "arrow implies then"],
  ["↩", "return arrow", "enter back"],
  ["⌘", "command key", "mac cmd apple"],
  ["⌥", "option key", "mac alt"],
  ["⇧", "shift key", "mac shift"],
  ["⌫", "backspace", "delete key"],
  ["⏎", "enter key", "return newline"],
  ["…", "ellipsis", "dots three"],
  ["—", "em dash", "dash long"],
  ["–", "en dash", "dash range"],
  ["·", "middle dot", "bullet separator"],
  ["•", "bullet", "list dot point"],
  ["§", "section", "paragraph legal"],
  ["©", "copyright", "legal"],
  ["®", "registered", "trademark legal"],
  ["™", "trademark", "tm brand"],
  ["✓", "check", "tick yes done ok"],
  ["✔", "heavy check", "tick done"],
  ["✗", "ballot x", "cross no wrong"],
  ["°", "degree", "temperature angle"],
  ["±", "plus minus", "tolerance approx"],
  ["×", "multiply", "times cross product"],
  ["÷", "divide", "division"],
  ["≈", "approximately", "almost equal approx"],
  ["≠", "not equal", "different"],
  ["≤", "less or equal", "lte at most"],
  ["≥", "greater or equal", "gte at least"],
  ["∞", "infinity", "endless"],
  ["√", "square root", "sqrt radical"],
  ["∑", "sum", "sigma total"],
  ["π", "pi", "circle constant"],
  ["µ", "micro", "mu"],
  ["€", "euro", "currency money eur"],
  ["£", "pound sterling", "currency money gbp"],
  ["¥", "yen", "currency money jpy yuan"],
  ["₩", "won", "currency money krw korea"],
  ["₿", "bitcoin", "currency crypto btc"],
  ["★", "black star", "favorite rating"],
  ["☆", "white star", "favorite rating outline"],
  ["♥", "heart suit", "cards love"],
  ["☑", "ballot check", "checkbox done"],
  ["⬜", "white square", "block empty"],
  ["⬛", "black square", "block filled"],
]

export type EmojiMatch = { char: string; name: string; score: number }

const DEFAULT_LIMIT = 30

export const matchEmoji = (
  query: string,
  limit = DEFAULT_LIMIT,
): EmojiMatch[] => {
  const needle = query.trim()

  if (!needle) {
    return TABLE.slice(0, limit).map(([char, name], i) => ({
      char,
      name,
      score: limit - i,
    }))
  }

  return TABLE.map(([char, name, keywords]) => ({
    char,
    name,
    score: Math.max(
      score(name, needle),
      ...keywords.split(" ").map(word => score(word, needle) * 0.9),
    ),
  }))
    .filter(match => match.score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, limit)
}
